#!/bin/sh -e

PREREQS="udev"

prereqs() { echo "$PREREQS"; }

case "$1" in
    prereqs)
    prereqs
    exit 0
    ;;
esac

. /usr/share/initramfs-tools/hook-functions

#load config file
conf_file="/etc/raspi-updater/raspi-updater.conf"
. "$conf_file"

# copy files to /boot
boot_dir="/boot/raspi-updater"
mkdir -p "$boot_dir"
cp "$conf_file" "$boot_dir/"
cp /usr/share/raspi-updater/initramfs-script "$boot_dir/"
cp /usr/share/raspi-updater/raspi-updater  "$boot_dir/"
cp "$CERT_FILE" "$boot_dir/"

# copy information of /boot to ramdisk
BOOTDEVICE=$(df -P "$boot_dir" | tail -n1 | awk '{print $1}')
BOOTMOUNT=$(df -P "$boot_dir" | tail -n1 | awk '{print $6}')
BOOTUPDATERDIR=${boot_dir#"${BOOTMOUNT}"}
FSTYPE=$(blkid -o value -s TYPE "$BOOTDEVICE" || true)

mkdir -p "$DESTDIR/etc/raspi-updater"
cat <<EOF > "$DESTDIR/etc/raspi-updater/boot.conf"
BOOTDEVICE=$BOOTDEVICE
BOOTMOUNT=$BOOTMOUNT
BOOTUPDATERDIR=$BOOTUPDATERDIR
FSTYPE=$FSTYPE
EOF

# ordered by prefered order
for tool in lz4 zstd gzip xz; do
    if [ ! -f "/usr/bin/$tool" ]; then
        continue
    fi
    copy_exec "/usr/bin/$tool"   /usr/bin
    tool_copied=true
done

if [ "${tool_copied:-}" != "true" ]; then
    echo "No valid compressor tool found"
    exit 1
fi

# for setting IP from DHCP client (requires udhcpc)
mkdir -p "$DESTDIR/etc/udhcpc"
cp -p "/etc/udhcpc/default.script" "$DESTDIR/etc/udhcpc"

# For DNS resolving
cp -p /etc/hosts "$DESTDIR/etc"
cp -p /etc/resolv.conf "$DESTDIR/etc"
cp -p /etc/nsswitch.conf "$DESTDIR/etc"

# In case busybox did not create symlinks...
ln -sf "/bin/busybox" "$DESTDIR/bin/partprobe"

if echo "$NET_INTERFACE" | grep '^wlan'; then
    mkdir -p "$DESTDIR/usr/sbin" \
        "$DESTDIR/etc/wpa_supplicant" \
        "$DESTDIR/usr/lib/firmware"

    cp -rp "/usr/lib/firmware/brcm"  "$DESTDIR/usr/lib/firmware"
        
    copy_exec /usr/sbin/wpa_supplicant    /usr/sbin
    # cp -p "/etc/wpa_supplicant/wpa_supplicant.conf" "$DESTDIR/etc/wpa_supplicant"
    sed '/^ctrl_interface.*/d' /etc/wpa_supplicant/wpa_supplicant.conf \
        > "$DESTDIR/etc/wpa_supplicant/wpa_supplicant.conf"
    
    # wpa_supplicant expects /var/run
    mkdir -p "$DESTDIR/var"
    ln -sf /run "$DESTDIR/var/run"
    # cp -p "/etc/group" "/etc/passwd"  "$DESTDIR/etc"
fi

# add net driver and filesystem drivers
manual_add_modules "$NET_DRIVER" ext4 vfat