#!/bin/sh -e

PREREQS="udev"

prereqs() { echo "$PREREQS"; }

case "$1" in
    prereqs)
    prereqs
    exit 0
    ;;
esac

. /usr/share/initramfs-tools/hook-functions

#load config file
conf_file="/etc/raspi-updater/raspi-updater.conf"
. "$conf_file"

# copy files to /boot
boot_dir="/boot/raspi-updater"
mkdir -p "$boot_dir"
cp -p "$conf_file" "$boot_dir/"
cp -p /usr/share/raspi-updater/initramfs-script "$boot_dir/"
cp -p /usr/share/raspi-updater/raspi-updater  "$boot_dir/client-raspi-updater"
cp -p "$CERT_FILE" "$boot_dir/"

copy_exec "/usr/bin/$COMPRESSION_TOOL"   /usr/bin

# for setting IP from DHCP client (requires udhcpc)
mkdir -p "$DESTDIR/etc/udhcpc"
cp -p "/etc/udhcpc/default.script" "$DESTDIR/etc/udhcpc"

# For DNS resolving
cp -p /etc/resolv.conf "$DESTDIR/etc"
cp -p /etc/nsswitch.conf "$DESTDIR/etc"

# In case busybox did not create symlinks...
ln -sf "/bin/busybox" "$DESTDIR/bin/partprobe"

if echo "$NET_INTERFACE" | grep '^wlan'; then
    mkdir -p "$DESTDIR/usr/sbin" \
        "$DESTDIR/etc/wpa_supplicant" \
        "$DESTDIR/usr/lib/firmware"

    cp -rp "/usr/lib/firmware/brcm"  "$DESTDIR/usr/lib/firmware"
        
    copy_exec /usr/sbin/wpa_supplicant    /usr/sbin
    # cp -p "/etc/wpa_supplicant/wpa_supplicant.conf" "$DESTDIR/etc/wpa_supplicant"
    sed '/^ctrl_interface.*/d' /etc/wpa_supplicant/wpa_supplicant.conf \
        > "$DESTDIR/etc/wpa_supplicant/wpa_supplicant.conf"
    
    # wpa_supplicant expects /var/run
    mkdir -p "$DESTDIR/var"
    ln -sf /run "$DESTDIR/var/run"
    # cp -p "/etc/group" "/etc/passwd"  "$DESTDIR/etc"
fi

# add net driver and filesystem drivers
manual_add_modules "$NET_DRIVER" ext4 vfat