#!/bin/sh -e

PREREQS="udev"

prereqs() { echo "$PREREQS"; }

case "$1" in
    prereqs)
    prereqs
    exit 0
    ;;
esac

. /usr/share/initramfs-tools/hook-functions

mkdir -p "$DESTDIR/etc/raspi-updater"
cp -p "/etc/raspi-updater/raspi-updater.conf" "$DESTDIR/etc/raspi-updater"

# for setting IP from DHCP client (requires udhcpc)
mkdir -p "$DESTDIR/etc/udhcpc"
cp -p "/etc/udhcpc/default.script" "$DESTDIR/etc/udhcpc"

# For DNS resolving
cp -p /etc/resolv.conf "$DESTDIR/etc"
cp -p /etc/nsswitch.conf "$DESTDIR/etc"

# In case busybox did not create symlinks...
ln -sf "/bin/busybox" "$DESTDIR/bin/partprobe"

. "/etc/raspi-updater/raspi-updater.conf"

mkdir -p "$DESTDIR/usr/bin"
cp -p /usr/share/raspi-updater/initramfs-script "$DESTDIR/usr/bin/raspi-updater-script"
chmod +x "$DESTDIR/usr/bin/raspi-updater-script"

copy_exec /usr/share/raspi-updater/raspi-updater      /usr/bin/client-raspi-updater
copy_exec "/usr/bin/$COMPRESSION_TOOL"   /usr/bin

cert_file_dir="$DESTDIR/$(dirname "$CERT_FILE")"
mkdir -p "$cert_file_dir"
cp -p "$CERT_FILE" "$cert_file_dir"


if echo "$NET_INTERFACE" | grep '^wlan'; then
    mkdir -p "$DESTDIR/usr/sbin" \
        "$DESTDIR/etc/wpa_supplicant" \
        "$DESTDIR/usr/lib/firmware"

    cp -rp "/usr/lib/firmware/brcm"  "$DESTDIR/usr/lib/firmware"
        
    copy_exec /usr/sbin/wpa_supplicant    /usr/sbin
    cp -p "/etc/wpa_supplicant/wpa_supplicant.conf" "$DESTDIR/etc/wpa_supplicant"
fi

# add net driver
manual_add_modules "$NET_DRIVER"