#!/bin/sh

set -e

# Install systemd service
if [ ! -f /.dockerenv ]; then
    /usr/bin/systemctl daemon-reload
    /usr/bin/systemctl enable raspi-updater.service
    /usr/bin/systemctl start raspi-updater.service
fi

exit 0