#!/bin/sh
# shellcheck disable=SC1091,SC2015
set -e

case "${1}" in
prereqs)
    exit 0 ;;
esac

/usr/bin/raspi-updater-initramfs-script 2>&1 | tee /run/raspi-updater.log || echo script returned error.